### ISSUE TITLE
Calendar always displays exact same month/week

### ISSUE THREAD

**Issue by Morrodin** [kizitonwose/CalendarView#134]
Hello,

I'm trying to implement a calendar very similar to the one in your Example 1, which can swap between month and week. With that in mind, I'm trying to initialize and configure it with almost identical settings (at least to begin with, while I learn what I'm doing). 

However, I'm running into an interesting issue. The Calendar is always drawing the exact same month (or week, depending on mode), no matter what dates I pass in or try to scroll to (via `scrollToDate`). The dates it seems to always be pulling from seem to to be from my `startMonth` (which I'm initializing to `currentMonth.minusMonths(10)`, like in Example 1).

`calendarView.findFirstVisibleDate()` always returns it, and if I set a breakpoint in my dayBinder, i can see that it always returns the same set of dates, no matter what I've tried to scroll through.

I'm sure this has to be some kind of user error on my part, since I was able to modify Example 1 to i.e. scroll forward a week at a time with no issue. I'm feeling stumped when it comes to what I'm doing wrong in my own code, though.

Here's a gist with my custom view I wrote around CalendarView (in an effort to keep my activity a bit cleaner): https://gist.github.com/Morrodin/e2b86231f2d254751d4d633b03313626

Thanks in advance for any help!

**Comment by Morrodin** [comment]
Alright, after swapping over to an extremely reduced test case in a brand new app using just my `ScheduleCalendarView` wrapper, I've learned a few things.

1. I can't call `scrollToDate` until the very end of my setup method. If I do this, it starts the `CalendarView` on the correct date.
2. My arrows work as expected if I call `smoothScrollToDate` vs `scrollToDate`. If I call `scrollToDate` the dates never change.

This accomplishes what I need it to (I want smooth scroll for the arrows anyways), so I guess you could consider my issue "solved". I do admit confusion as to _why_ I had to change these specific things/certain things don't work.

Cheers.

**Comment by kizitonwose** [comment]
I see you already sorted out the problem. Some input anyways:

- `scrollToDate` will not work with ScrollMode.PAGED because the view will snap to fit the entire month, so unless the date is the first in the month, you may think it's not working properly.

- As noticed, `scrollToDate` or any scroll method for that matter will work only after setup because the calendar needs to find the date internally before scrolling to its position.

- When, `hasBoundaries = false`, the underlying Month is undefined on all indices as each index could have multiple months. I'm considering ways to improve this particular one or make it clearer at least, not sure what to do yet.

**Comment by kizitonwose** [comment]
Can I close this now?

**Comment by Morrodin** [comment]
Yes, thank you. That clarifies some things.
