### ISSUE TITLE
Allow updating of in/out dates

### ISSUE THREAD

**Issue by DantheCodingGui** [kizitonwose/CalendarView#25]
Hi, 

I'm working on a calendar that will require inDates and outDates to be selectable.

I've noticed that when notifyDateChanged is called it will only rebind the day view container of the date in it's own month. This means that if I click on an inDate or outDate it's container won't update.

Could something be added to allow inDates and outDates to also be rebound?

**Comment by kizitonwose** [comment]
This is correct, if you look at the source code, calling `notifyDateChanged()` simply calls `notifyDayChanged(CalendarDay(date, DayOwner.THIS_MONTH))`, meaning that you cannot reload in/out dates using `notifyDateChanged()`. 

If you want to reload in/out dates, you need to use a `CalendarDay` which represents that in/out date. When you click on a date cell, you are given the associated `CalendarDay` instance, you can store a reference to this and use `notifyDayChanged()` when reloading instead of `notifyDateChanged()`
