### ISSUE TITLE
Make CalendarDay Open

### ISSUE THREAD

**Issue by DantheCodingGui** [kizitonwose/CalendarView#26]
I'm running into a problem regarding selecting indates/outdates.

Using `CalendarView.notifyDayChanged()`  I can show an indate/outdate as selected. Combining this with `notifyDateChanged()` when an indate/outdate is selected and you scroll to it's month, it is selected there as well.

The problem lies when you select a day in this month (ie. not an indate/outdate), if that date exists as an indate/outdate in another month, when you scroll to it, it won't be selected and there doesn't seem to be a way to do it.

I can think of getting this to work if when selecting any date, I call `notifyDayChanged()` with all 3 owners, but that would require the ability to instantiate new CalendarDay objects with the same `LocalDate` but different owners. 

Is there an alternative way of doing this?, 
thanks.

**Comment by kizitonwose** [comment]
Instead of making the `CalendarDay` class constructor public, [version 0.2.2](https://github.com/kizitonwose/CalendarView/releases/tag/0.2.2) allows you to optionally specify an owner when reloading a date:
 
`fun notifyDateChanged(date: LocalDate, owner: DayOwner = DayOwner.THIS_MONTH)` 

The `CalendarDay` class can become more complex in the future, so it's important that it's only created internally.

**Comment by DantheCodingGui** [comment]
Thanks! That should do the trick
