### ISSUE TITLE
Sticky headers

### ISSUE THREAD

**Issue by acolombo25** [kizitonwose/CalendarView#33]
In my vertical scrolling calendar (similar to example2) I would like to have sticky headers. I've tried using [this solution](https://gist.github.com/filipkowicz/1a769001fae407b8813ab4387c42fcbd) making a custom RecyclerView.ItemDecoration but, with "CalendarAdapter" being internal and not using the "viewType" parameter, I find it really difficult to make it work . Do you have any suggestions in how to implement such a thing? Internal or external to the library I could implement it myself, I'm just seeking some advice.

**Comment by kizitonwose** [comment]
I played around with example 2 to achieve something like this. Since `CalendarView` extends from `RecyclerView`, I added a scroll lister and just updated a view which I put above the weekday texts on the toolbar. 

**Here's the result:**

<img src="https://user-images.githubusercontent.com/15170090/61657133-27045280-acba-11e9-9ae7-21a69a06fa7b.gif" alt="Sticky header" width="280">

**Comment by acolombo25** [comment]
It's not exactly what I wanted because using the previously mentioned RecyclerView.ItemDecoration the current header gets pushed away from the previous one. But still the result you helped me getting is totally acceptable, so thank you really much.

Here's the result:
![ScreenRecord_20190724-121133_1](https://user-images.githubusercontent.com/9468299/61786015-2fb96d80-ae0d-11e9-8faa-7f598e36c6e4.gif)
.

**Comment by kizitonwose** [comment]
Glad I was able to help! Closing this now.
