### ISSUE TITLE
Unable to change language based on app language 

### ISSUE THREAD

**Issue by Mrityunjayri** [kizitonwose/CalendarView#365]
When i am change my app language that time calender view not changing the language, but after the kill application from background it working fine.

**Comment by kizitonwose** [comment]
I use the library in an app as well and do not have this problem (see video).

My guess is that you are not using the updated Locale when creating the calendar (header texts, first day of the week etc). For example, instead of `Locale.getDefault()` you can use the locale in the view/fragment/activity context `context.resources.configuration.locales.get(0)` as that gets updated when the device locale changes.

You should also ensure you are not storing a reference to the Locale beyond the view/fragment/activity scope as that will not be updated.

https://user-images.githubusercontent.com/15170090/160232223-3f670779-6c70-4884-83cb-2868ec16dc28.mp4

**Comment by Mrityunjayri** [comment]
thanks it working

[image: photo]

*Mrityunjay Patel*
*Customer support*

*Wheelseye Technology India Private Limited*

*+91 8 <+91%208929356942>468965906*

***@***.***

www.wheelseye.com

Unit No 203 | 2nd Floor SAS TOWER, Near Medanta Hospital, Sector - 38
Gurugram - 122001
