### ISSUE TITLE
Feature request: Add ability to update a group of days in the calendar

### ISSUE THREAD

**Issue by AdibaM** [kizitonwose/CalendarView#55]
Love this library and I'm making a lot of cool progress with it. 

At the moment there are few methods to notify changes:

_notifyDayChanged()_,  _notifyMonthChanged()_ , _notifyCalendarChanged()_ ...

It would be nice to have a method which does this for a range of days or a group of days within a month or group of days in the calendar.

**Comment by kizitonwose** [comment]
I had this during the initial development of the library. For example, the method for reloading multiple dates simply looped through the dates and calls `notifyDayChanged()` for each. It just seemed more noisy than useful so I removed it. 

The idea may be useful for reloading a range by providing the start and end dates by that's tricky because if the calendar has in and out dates and the provided range spans multiple months, then the in/out dates have to be generated and reloaded too. All that work seems too much when the user can just specify what needs to be reloaded.

**Comment by kizitonwose** [comment]
I'll close this for now. Will reopen if necessary in the future.
