### ISSUE TITLE
Multi-day events

### ISSUE THREAD

**Issue by StevenKek** [kizitonwose/CalendarView#79]
Hi, how would I go about creating events that span across multiple days?
Something like [the red event here](https://cdn0.tnwcdn.com/wp-content/blogs.dir/1/files/2015/04/gcal-android-month-cropped-730x506.png).

Thanks

**Comment by kizitonwose** [comment]
The trick in your binding logic. You can check if the next calendar day has the same event and show a view with the event color if it does. Then on the first day of the event, and you can find this by checking for the date whose previous day does not have the same event, you show the text for that event.

Not sure if my explanation is clear but I hope you get the idea.

**Comment by StevenKek** [comment]
Makes sense, I will do just that. Your explanation is crystal clear, thanks! :)

One more thing - can I make the text from the first day overlap into the second day as well?
Maybe I can disable view clipping (if Android allows that) and let the TextView for the first day simply expand it's width without boundaries. And set max character count so that it doesn't go too far. And somehow make sure it doesn't leave calendar bounds in case the first day of the event is the last day in week.

**Comment by kizitonwose** [comment]
I was gonna say it's not possible but after a much deeper thought it seems you can actually achieve this if you're a bit adventurous 😆😆😆

While you can't disable clipping as you have described since each TextView will be in its own ViewGroup, if you know every date where the label spans across(you can find this using the logic in my previous comment), you can get the TextViews, calculate the max text that can fit in each of them and set the texts separately..

I just tested a proof of concept where I have multiple TextView's in a LinearLayout which is the root layout like this:

```xml
<LinearLayout
    android:id="@+id/textLayout"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:orientation="vertical">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textSize="22sp" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textSize="22sp" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textSize="22sp" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textSize="22sp" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textSize="22sp" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:textSize="22sp" />
</LinearLayout>
```

Then I set the max text for each TextView like this:
```kotlin
val displayMetrics = DisplayMetrics()
val windowManager = requireContext().getSystemService(Context.WINDOW_SERVICE) as WindowManager
windowManager.defaultDisplay.getMetrics(displayMetrics)

var text = "This is a long text that I want to split across multiple text views. Each TextView should take only as much text that it can fit on a single line"
var index = 0
while (text.isNotEmpty()) {
    val nextTextView = textLayout.children.toList()[index] as TextView
    val count = nextTextView.paint.breakText(text, true, displayMetrics.widthPixels.toFloat(), null)
    val newText = text.take(count)
    text = text.drop(count)
    nextTextView.text = newText
    index++
}
```

I have used the screen width(`displayMetrics.widthPixels`) for the max width at which I want the text to break in this use case, but for the calendar date cells, you'd have to divide this by 7 to get the desired width.

It's a bit rough but it may be a starting point. Also since you can't explicitly request for a date's view, you can perform this calculation, store your split strings in an array, then reload the corresponding dates and set text accordingly.

**Comment by kizitonwose** [comment]
Looks like this can be closed now. Still let me know the "adventure" turned out. 🤞🤞

**Comment by fukemy** [comment]
hi can u make function to commit to the master? Thanks
