### ISSUE TITLE
notifyDateChanged() only updates it's specific month

### ISSUE THREAD

**Issue by eldorak90** [kizitonwose/CalendarView#86]
I am implementing a calendar with your library and noticed, that CalendarView.notifyDateChanged() only updates the given day of that month, e.g called for 2019-11-28, it only updates the view of that day in November. When I switch to December, the 28th of November as an InDate didn't update. When I scroll through the calendar and back, it sometimes get's updated (probably after a redraw of that month).
I'd expect to update all views of that specific day.
It works by calling CalendarView.notifyCalendarChanged(), but I'd prefer to update only that day, instead of the whole calendar

**Comment by kizitonwose** [comment]
This is working as expected. You are notifying the calendar that a specific date has changed. 2019-11-28 and 2019-12-28 are **NOT** the same. If you want to reload both dates as in your example, you must call notifyDateChanged with both date instances.

**Comment by kizitonwose** [comment]
Closing this as it is working as expected.

**Comment by eldorak90** [comment]
That isn't what I meant.
2019-11-28 is shown on both, November and December. In December in form of an InDate.
When I call notifyDateChanged() on 28th of  November, it Updates the 28th of November on November page, but It doesn't update the 28th of November on December page.

**Comment by kizitonwose** [comment]
This is because the date owners are different and you are supposed to pass in the date owner when reloading a date. The default value as seen in the method signature for `notifyDateChanged()` is `DayOwner.THIS_MONTH` which reloads the date in the month which "owns" it. If you want to reload the date for all months, you would need to call:

```kotlin
notifyDateChanged(date, DayOwner.THIS_MONTH)
notifyDateChanged(date, DayOwner.PREVIOUS_MONTH)
notifyDateChanged(date, DayOwner.NEXT_MONTH)
```
Again, this is a design decision that allows us to reload only what we want, and you can see in all the examples that I never had to call all three. Imagine if all instances were reloaded automatically what a waste it would be.

If calling all three methods seem tedious for you, you can write an extension function that you can call whenever you want. Something like:
```kotlin
fun CalendarView.notifyDateChangedForAll(date: LocalDate) {
    notifyDateChanged(date, DayOwner.THIS_MONTH)
    notifyDateChanged(date, DayOwner.PREVIOUS_MONTH)
    notifyDateChanged(date, DayOwner.NEXT_MONTH)
}
```
Now you can just call:
```kotlin
calendarView.notifyDateChangedForAll(date)
```

**Comment by eldorak90** [comment]
Nice, this seems to work. Thanks
